import { VideoProject } from "../types";

export const DNA_REPLICATION_FIXTURE: VideoProject = {
  id: "fixture-dna-replication",
  prompt: "How DNA replication works step-by-step",
  title: "Molecular Mechanism of DNA Replication",
  learningObjective: "Understand helicase unzipping, RNA priming, and leading/lagging strand synthesis",
  audienceLevel: "intermediate",
  aspectRatio: "16:9",
  voiceover: "nova",
  bgMusic: "none",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  scenes: [
    {
      id: "dna-scene-1",
      sceneNumber: 1,
      title: "1. The Double Helix Architecture",
      purpose: "Establish molecular structure of double-stranded DNA",
      narration: "Deoxyribonucleic acid is composed of two antiparallel strands forming a double helix held together by hydrogen bonds between complementary base pairs.",
      duration: 12,
      rendererType: "hero3d",
      visualLanguage: {
        theme: "dark",
        primaryColor: "#38BDF8",
        secondaryColor: "#818CF8",
        accentColor: "#34D399",
      },
      visualPrimitives: [
        {
          id: "3d-dna",
          type: "3d-model",
          modelType: "dna-helix",
          label: "B-DNA Double Helix",
          detail: "3.4 nm helical pitch",
          x: 0.5,
          y: 0.45,
        },
        {
          id: "card-1",
          type: "node",
          label: "Antiparallel Strands",
          detail: "5' to 3' and 3' to 5'",
          x: 0.15,
          y: 0.35,
        },
        {
          id: "card-2",
          type: "node",
          label: "Complementary Pairs",
          detail: "Adenine-Thymine, Guanine-Cytosine",
          x: 0.85,
          y: 0.35,
        },
      ],
      animationBeats: [
        { timestamp: 0.1, action: "enter", targetId: "3d-dna" },
        { timestamp: 0.3, action: "highlight", targetId: "card-1" },
        { timestamp: 0.6, action: "highlight", targetId: "card-2" },
      ],
    },
    {
      id: "dna-scene-2",
      sceneNumber: 2,
      title: "2. Unzipping at the Replication Fork",
      purpose: "Show DNA Helicase breaking hydrogen bonds",
      narration: "DNA Helicase binds at the origin of replication, unwinding the double helix and breaking hydrogen bonds to form the Y-shaped replication fork.",
      duration: 14,
      rendererType: "process",
      visualLanguage: {
        theme: "dark",
        primaryColor: "#6366F1",
        secondaryColor: "#EC4899",
        accentColor: "#F59E0B",
      },
      visualPrimitives: [
        {
          id: "proc-node-1",
          type: "node",
          label: "Origin of Replication",
          detail: "AT-rich region bound by initiator proteins",
          x: 0.2,
          y: 0.5,
        },
        {
          id: "proc-node-2",
          type: "node",
          label: "DNA Helicase",
          detail: "Hexameric ring motor unzipping strands",
          x: 0.5,
          y: 0.5,
        },
        {
          id: "proc-node-3",
          type: "node",
          label: "Single-Strand Binding Proteins",
          detail: "Prevents re-annealing of template strands",
          x: 0.8,
          y: 0.5,
        },
        {
          id: "conn-1-2",
          type: "connection",
          label: "Binds",
          x: 0.35,
          y: 0.5,
        },
        {
          id: "conn-2-3",
          type: "connection",
          label: "Opens Fork",
          x: 0.65,
          y: 0.5,
        },
      ],
      animationBeats: [
        { timestamp: 0.1, action: "enter", targetId: "proc-node-1" },
        { timestamp: 0.3, action: "connect", targetId: "conn-1-2" },
        { timestamp: 0.5, action: "enter", targetId: "proc-node-2" },
        { timestamp: 0.7, action: "connect", targetId: "conn-2-3" },
        { timestamp: 0.85, action: "enter", targetId: "proc-node-3" },
      ],
    },
    {
      id: "dna-scene-3",
      sceneNumber: 3,
      title: "3. Leading & Lagging Strand Synthesis",
      purpose: "Compare continuous vs discontinuous synthesis",
      narration: "DNA Polymerase III synthesizes the leading strand continuously toward the fork, while the lagging strand is synthesized discontinuously into Okazaki fragments.",
      duration: 16,
      rendererType: "comparison",
      visualLanguage: {
        theme: "dark",
        primaryColor: "#10B981",
        secondaryColor: "#3B82F6",
        accentColor: "#8B5CF6",
      },
      visualPrimitives: [
        {
          id: "comp-left",
          type: "box",
          label: "Leading Strand (Continuous)",
          detail: "Synthesized 5' -> 3' direction toward replication fork. Requires single RNA primer.",
          x: 0.3,
          y: 0.45,
        },
        {
          id: "comp-right",
          type: "box",
          label: "Lagging Strand (Discontinuous)",
          detail: "Synthesized away from fork in Okazaki fragments. Joined by DNA Ligase.",
          x: 0.7,
          y: 0.45,
        },
      ],
      animationBeats: [
        { timestamp: 0.1, action: "enter", targetId: "comp-left" },
        { timestamp: 0.5, action: "enter", targetId: "comp-right" },
        { timestamp: 0.8, action: "highlight", targetId: "comp-right" },
      ],
    },
  ],
};

export const TRANSFORMER_FIXTURE: VideoProject = {
  id: "fixture-transformer",
  prompt: "The architecture of modern Transformer models in AI",
  title: "Transformer Neural Network Architecture",
  learningObjective: "Understand multi-head self-attention and encoder-decoder feedforward stacks",
  audienceLevel: "advanced",
  aspectRatio: "16:9",
  voiceover: "nova",
  bgMusic: "none",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  scenes: [
    {
      id: "trans-scene-1",
      sceneNumber: 1,
      title: "1. Self-Attention Neural Topology",
      purpose: "Visualize global token relationship graph",
      narration: "Transformers replace recurrent loops with self-attention, allowing every token in a sequence to connect directly to every other token in parallel.",
      duration: 12,
      rendererType: "hero3d",
      visualLanguage: {
        theme: "dark",
        primaryColor: "#8B5CF6",
        secondaryColor: "#EC4899",
        accentColor: "#38BDF8",
      },
      visualPrimitives: [
        {
          id: "3d-neural",
          type: "3d-model",
          modelType: "neural-net",
          label: "Multi-Head Attention Graph",
          x: 0.5,
          y: 0.45,
        },
        {
          id: "badge-1",
          type: "node",
          label: "Parallel Processing",
          detail: "O(1) sequential path length",
          x: 0.15,
          y: 0.4,
        },
        {
          id: "badge-2",
          type: "node",
          label: "Query, Key, Value Vectors",
          detail: "Q * K^T / sqrt(d_k)",
          x: 0.85,
          y: 0.4,
        },
      ],
      animationBeats: [
        { timestamp: 0.1, action: "enter", targetId: "3d-neural" },
        { timestamp: 0.4, action: "highlight", targetId: "badge-1" },
        { timestamp: 0.7, action: "highlight", targetId: "badge-2" },
      ],
    },
    {
      id: "trans-scene-2",
      sceneNumber: 2,
      title: "2. The Layer Stack Architecture",
      purpose: "Diagram input embeddings, multi-head attention, and feedforward blocks",
      narration: "Input tokens pass through positional encoding, multi-head self-attention, residual connections with layer normalization, and position-wise feedforward networks.",
      duration: 16,
      rendererType: "architecture",
      visualLanguage: {
        theme: "dark",
        primaryColor: "#6366F1",
        secondaryColor: "#10B981",
        accentColor: "#F59E0B",
      },
      visualPrimitives: [
        {
          id: "arch-layer-1",
          type: "box",
          label: "1. Input Token Embeddings + Positional Encoding",
          detail: "Vector dimension d_model = 512 / 4096",
          x: 0.5,
          y: 0.75,
        },
        {
          id: "arch-layer-2",
          type: "box",
          label: "2. Multi-Head Self-Attention + Add & Norm",
          detail: "h = 8 attention heads in parallel",
          x: 0.5,
          y: 0.5,
        },
        {
          id: "arch-layer-3",
          type: "box",
          label: "3. Position-wise Feedforward Network + Add & Norm",
          detail: "Linear -> GELU -> Linear transformation",
          x: 0.5,
          y: 0.25,
        },
      ],
      animationBeats: [
        { timestamp: 0.1, action: "enter", targetId: "arch-layer-1" },
        { timestamp: 0.4, action: "enter", targetId: "arch-layer-2" },
        { timestamp: 0.7, action: "enter", targetId: "arch-layer-3" },
      ],
    },
  ],
};

export const FRENCH_REVOLUTION_FIXTURE: VideoProject = {
  id: "fixture-french-revolution",
  prompt: "Timeline and key events of the French Revolution",
  title: "Chronology of the French Revolution (1789 - 1799)",
  learningObjective: "Trace the progression from absolute monarchy to radical republic and Napoleonic consulate",
  audienceLevel: "intermediate",
  aspectRatio: "16:9",
  voiceover: "nova",
  bgMusic: "none",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  scenes: [
    {
      id: "fr-scene-1",
      sceneNumber: 1,
      title: "1. Key Milestones of the Revolution",
      purpose: "Chronological timeline of major political shifts",
      narration: "The French Revolution erupted in 1789 with the Storming of the Bastille, leading to the collapse of feudalism, the Reign of Terror, and Napoleon's eventual rise.",
      duration: 18,
      rendererType: "timeline",
      visualLanguage: {
        theme: "dark",
        primaryColor: "#EF4444",
        secondaryColor: "#3B82F6",
        accentColor: "#F59E0B",
      },
      visualPrimitives: [
        {
          id: "event-1",
          type: "map-card",
          label: "July 14, 1789",
          detail: "Storming of the Bastille & Estates-General revolt",
          x: 0.18,
          y: 0.45,
        },
        {
          id: "event-2",
          type: "map-card",
          label: "August 1789",
          detail: "Declaration of the Rights of Man & Citizen",
          x: 0.38,
          y: 0.45,
        },
        {
          id: "event-3",
          type: "map-card",
          label: "1793 - 1794",
          detail: "Execution of Louis XVI & Reign of Terror",
          x: 0.62,
          y: 0.45,
        },
        {
          id: "event-4",
          type: "map-card",
          label: "November 1799",
          detail: "Coup of 18 Brumaire & Rise of Napoleon",
          x: 0.84,
          y: 0.45,
        },
      ],
      animationBeats: [
        { timestamp: 0.1, action: "enter", targetId: "event-1" },
        { timestamp: 0.35, action: "enter", targetId: "event-2" },
        { timestamp: 0.6, action: "enter", targetId: "event-3" },
        { timestamp: 0.85, action: "enter", targetId: "event-4" },
      ],
    },
  ],
};

export const ALL_FIXTURES: Record<string, VideoProject> = {
  "dna-replication": DNA_REPLICATION_FIXTURE,
  transformer: TRANSFORMER_FIXTURE,
  "french-revolution": FRENCH_REVOLUTION_FIXTURE,
};
